### ISSUE TITLE
Installation failed in windows.

### ISSUE THREAD

**Issue by shoebxsiddiqui** [starfixdev/starfix#100]
I followed the steps, but its not working, when i am typing starfix on command promt, its showing 'starfix' is not recognized as an internal or external command.

**Comment by zedbeit** [comment]
Starfix binary is not in your path. How did you install it?

**Comment by shoebxsiddiqui** [comment]
I downloaded the zip files, then extracted it, then followed the steps as given in the readme file.

**Comment by shoebxsiddiqui** [comment]
how to add that in the path?

**Comment by zedbeit** [comment]
Download the starfix build from here https://github.com/starfixdev/starfix/pull/93/checks and add the path to the starfix binary to your **Path** environment variable.

e.g: **C:\Users\Public\starfix** can be where I installed my starfix, so I just need to add it to Path.

**Comment by shoebxsiddiqui** [comment]
hey, i added it in user variable for hp and in system variable but still i am facing the same problem, i gave variable name as starfix and then copied the address of the project like G:\starfix in both user and system variable. BTW can u pls tell me what is this starfix binary.

And, https://github.com/starfixdev/starfix/pull/93/checks i installed the zip file from here and it only has the build and not the complete project.

**Comment by zedbeit** [comment]
There's actually a starfix channel on  zulip chat.  You can ask your questions there and you'll get sorted out. 
 https://quarkusio.zulipchat.com
