### ISSUE TITLE
Custom Launch Command for IDE

### ISSUE THREAD

**Issue by fahad-israr** [starfixdev/starfix#81]
- Shouldn't  starfix support a custom IDE launch command .
- Currently, while configuring preferred IDE/Editor we display to user a limited set of IDE and ask to chose from them . What if user wants to use some other Ide/editor .
- We can try to accept custom input from user (Eg user can enter`code` if he wants to use VSCode)  in addition to the existing Ide . Offcourse, then we need to think about the launch command format in that case . For that we can use  use a common launch format (`ide_name path/to/directory`) which is used by most of the Ide/Editor. If there's even more robust solution to this then we could use that too .

**Comment by fahad-israr** [comment]
@maxandersen what do you think about this ? Shall I proceed with this ?

**Comment by maxandersen** [comment]
Yes.
