### ISSUE TITLE
The browser extension doesn't do anything if the default configuration have not been set.

### ISSUE THREAD

**Issue by zedbeit** [starfixdev/starfix#97]
#### Description

Without initially setting the two **Starfix** configurable properties:- cloning path and preferred editor, using the `starfix config` command, the browser extension doesn't actually do anything.   

#### Implementation ideas

**Starfix** should be first configured. i.e. If you click on the link **Open in IDE** in the browser, it should open a window to configure your IDE and preferred editor first before going ahead.

**Comment by fahad-israr** [comment]
Starfix initially used to do the same but that was removed in the recent changes. Please configure it with `starfix config`

**Comment by zedbeit** [comment]
Oh okay. I think it would be helpful to newcomers if that is included in the README.

**Comment by maxandersen** [comment]
We really should make it so starfix does something on first call without needing config.

**Comment by fahad-israr** [comment]
That'd need us to have some default configs i.e IDE and Clone Path. VsCode can be the default IDE and `user-home/code`  can be default clone path . Previously we used to check if config exist and if not then we used to prompt user to configure. In the same way we can check if config exist and if not then we'd choose our default configs. 

A better way would be to figure out installed IDE on user's machine and launch one of it. @maxandersen can you suggest a good way to figure that out? OR using VsCode or any other IDE as preferred IDE is okay ?

**Comment by maxandersen** [comment]
Search path for known ide names and pick first found should be sufficient imo. 

Can even scan existing running processes and/or look for socket open where IntelliJ and eclipse listens.

**Comment by zedbeit** [comment]
This will be awesome. I'd like to take on this task.

**Comment by fahad-israr** [comment]
@zedbeit thumbs up .Go ahead !!

**Comment by zedbeit** [comment]
As this now has been implemented, I'll go ahead and close this issue.
